name: Feature Request
description: Suggest a new feature or enhancement for Quickshell
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request Guidelines

        Thanks for helping improve Quickshell!  
        Before submitting:
        - 🔍 Search [existing feature requests](https://github.com/quickshell-mirror/quickshell/discussions/categories/feature-requests)
        - 📌 Read the [pinned Feature Requests post](https://github.com/quickshell-mirror/quickshell/discussions/56)
        - 🏷️ Make sure your request is tagged with `feature` and `unresolved`
        - ❌ Untagged or unclear requests may be closed

  - type: input
    id: title
    attributes:
      label: Feature title
      description: A clear, concise summary of your feature idea
      placeholder: "Add a global keyboard shortcut for switching layouts"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Describe the feature and why it would be useful
      placeholder: I would like a feature that...
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use cases
      description: Describe scenarios or problems this feature would solve
      placeholder: This feature would help when I...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add screenshots, links, or anything else that helps explain your request
      placeholder: (optional)
